/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    offertes: Offerte;
    'check-aanvragen': CheckAanvragen;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    offertes: OffertesSelect<false> | OffertesSelect<true>;
    'check-aanvragen': CheckAanvragenSelect<false> | CheckAanvragenSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('nl' | 'en') | ('nl' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'nl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Editors manage content. Admins also manage users.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the image for screen readers and when the image can’t load. Important for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Page sections rendered on the site, in order.
   */
  layout?:
    | (
        | HeroBlock
        | ServicesBlock
        | PricingBlock
        | CtaBlock
        | ContactBlock
        | AccordionBlock
        | ButtonRowBlock
        | RichTextBlock
        | NoteBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * When on, search engines are asked not to index or follow this page.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  buttons?:
    | {
        /**
         * The text shown on the button.
         */
        label: string;
        /**
         * Visual style of the button.
         */
        variant?: ('primary' | 'secondary') | null;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Anchor ID of a section on the selected page (e.g. “prijzen”). Lowercase letters, numbers and dashes.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  cards?:
    | {
        /**
         * Search and pick a Tabler icon. Leave empty to use the block’s default icon.
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  tiers?:
    | {
        name: string;
        /**
         * Short line describing who this tier is for.
         */
        for?: string | null;
        price?: string | null;
        per?: string | null;
        /**
         * e.g. “or €1.210 per year (1 month free)”.
         */
        priceNote?: string | null;
        recommended?: boolean | null;
        /**
         * Small badge shown on the highlighted tier, e.g. “Aanbevolen”.
         */
        badge?: string | null;
        features?:
          | {
              text: string;
              included?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  eyebrow?: string | null;
  title: string;
  text?: string | null;
  button: {
    /**
     * The text shown on the button.
     */
    label: string;
    /**
     * Visual style of the button.
     */
    variant?: ('primary' | 'secondary') | null;
    /**
     * Link to a page on this site (follows the page if its address changes) or to an external web address.
     */
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    /**
     * Full web address, including https://
     */
    url?: string | null;
    /**
     * Optional. Anchor ID of a section on the selected page (e.g. “prijzen”). Lowercase letters, numbers and dashes.
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  items?:
    | {
        kind?: ('email' | 'phone' | 'address' | 'text') | null;
        label?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  buttons?:
    | {
        /**
         * The text shown on the button.
         */
        label: string;
        /**
         * Visual style of the button.
         */
        variant?: ('primary' | 'secondary') | null;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Anchor ID of a section on the selected page (e.g. “prijzen”). Lowercase letters, numbers and dashes.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  items?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock".
 */
export interface ButtonRowBlock {
  buttons?:
    | {
        /**
         * The text shown on the button.
         */
        label: string;
        /**
         * Visual style of the button.
         */
        variant?: ('primary' | 'secondary') | null;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Anchor ID of a section on the selected page (e.g. “prijzen”). Lowercase letters, numbers and dashes.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  alignment?: ('left' | 'center' | 'right') | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buttonRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  header?: {
    /**
     * Small line of text shown above the title.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Introductory paragraph shown below the title.
     */
    intro?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  width?: ('narrow' | 'wide') | null;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NoteBlock".
 */
export interface NoteBlock {
  text: string;
  /**
   * Optional. Gives this section an id so a menu item can scroll to it (e.g. “over-ons”). Use lowercase letters, numbers and dashes.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'note';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offertes".
 */
export interface Offerte {
  id: number;
  bedrijf: string;
  naam: string;
  email: string;
  subscription?: ('care' | 'beheerd' | 'partner' | 'opmaat') | null;
  additions?: ('localization' | 'email' | 'design' | 'seo' | 'content' | 'other')[] | null;
  additionsOther?: string | null;
  bericht?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "check-aanvragen".
 */
export interface CheckAanvragen {
  id: number;
  url: string;
  naam: string;
  telefoon: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'offertes';
        value: number | Offerte;
      } | null)
    | ({
        relationTo: 'check-aanvragen';
        value: number | CheckAanvragen;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        buttonRow?: T | ButtonRowBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        note?: T | NoteBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  tiers?:
    | T
    | {
        name?: T;
        for?: T;
        price?: T;
        per?: T;
        priceNote?: T;
        recommended?: T;
        badge?: T;
        features?:
          | T
          | {
              text?: T;
              included?: T;
              id?: T;
            };
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  text?: T;
  button?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  items?:
    | T
    | {
        kind?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        intro?: T;
      };
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock_select".
 */
export interface ButtonRowBlockSelect<T extends boolean = true> {
  buttons?:
    | T
    | {
        label?: T;
        variant?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  alignment?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  content?: T;
  width?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NoteBlock_select".
 */
export interface NoteBlockSelect<T extends boolean = true> {
  text?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offertes_select".
 */
export interface OffertesSelect<T extends boolean = true> {
  bedrijf?: T;
  naam?: T;
  email?: T;
  subscription?: T;
  additions?: T;
  additionsOther?: T;
  bericht?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "check-aanvragen_select".
 */
export interface CheckAanvragenSelect<T extends boolean = true> {
  url?: T;
  naam?: T;
  telefoon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Logo shown at the top-left of the header. Leave empty to use the default logo.
   */
  logo?: (number | null) | Media;
  /**
   * The navigation links shown in the header, in order.
   */
  navItems?:
    | {
        /**
         * The text shown on the link.
         */
        label: string;
        /**
         * Link to a page on this site (follows the page if its address changes) or to an external web address.
         */
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * Full web address, including https://
         */
        url?: string | null;
        /**
         * Optional. Anchor ID of a section on the selected page (e.g. “prijzen”). Lowercase letters, numbers and dashes.
         */
        anchor?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The button on the right side of the header. Leave the label empty to hide it.
   */
  cta?: {
    /**
     * The text shown on the link.
     */
    label?: string | null;
    /**
     * Link to a page on this site (follows the page if its address changes) or to an external web address.
     */
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    /**
     * Full web address, including https://
     */
    url?: string | null;
    /**
     * Optional. Anchor ID of a section on the selected page (e.g. “prijzen”). Lowercase letters, numbers and dashes.
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Logo shown in the footer. Leave empty to use the default logo.
   */
  logo?: (number | null) | Media;
  tagline?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  kvk?: string | null;
  btw?: string | null;
  menuItems?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  infoLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  address?: T;
  kvk?: T;
  btw?: T;
  menuItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  infoLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}